---
title: "Different Approaches to Crash Data Visualization"
author: "Ashirwad Barnwal"
date: "8/30/2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include = FALSE}
# Set global options
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(htmltools.dir.version = FALSE)

# Load packages
library(conflicted)
library(here)
library(tidyverse)
conflict_prefer("filter", "dplyr")
library(rio)
library(lubridate)
library(USAboundaries)
library(sf)
library(leaflet)
library(leaflet.extras)
library(mapview)
library(leafem)
library(leafsync)
library(knitr)

# Import crash data
fatal_crashes <- import(here("data", "ia-fatal-crashes-2015-19.rds"))
fatal_crashes_2019 <- filter(fatal_crashes, crash_year == 2019) %>%
  mutate(
    month = month(crash_date),
    season = if_else(month %in% c(5:10), "summer", "winter")
  )

# Iowa state & county boundaries
state_boundary <- st_geometry(us_states(resolution = "high", states = "IA"))
county_boundaries <- st_geometry(
  us_counties(resolution = "high", states = "IA")
)

# Create a basemap
basemap <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = state_boundary, fill = FALSE, group = "Boundaries") %>%
  addHomeButton(ext = st_bbox(state_boundary), group = "Zoom to Iowa")
```

---
# What is Leaflet?

```{r leaflet-url}
include_url("https://leafletjs.com/", height = "475px")
```

---
# Leaflet for R

```{r leaflet-rstudio-url}
include_url("https://rstudio.github.io/leaflet/", height = "475px")
```

---
# Fatal crashes as circles

```{r circles, out.width = "100%"}
(
circles <- basemap %>%
  addCircles(data = fatal_crashes_2019)
)
```

---
# Fatal crashes as marker clusters

```{r marker-clusters, out.width = "100%"}
(
marker_clusters <- basemap  %>%
  addCircleMarkers(
    data = fatal_crashes_2019, clusterOptions = markerClusterOptions()
  )
)
```

---
# Fatal crashes as a heatmap

```{r heatmap, out.width = "100%"}
(
heatmap <- basemap %>%
  addHeatmap(data = fatal_crashes_2019, radius = 10)
)
```

---
# Fatal crashes as a choropleth map

```{r choropleth, out.width = "100%"}
# Find the number of fatal crashes by county
fatal_crashes_2019_by_county <- county_boundaries %>%
  st_as_sf() %>%
  mutate(n_crashes = lengths(st_contains(., fatal_crashes_2019)))

# Define color palette
color_pal <- colorBin(
  "viridis",
  domain = fatal_crashes_2019_by_county$n_crashes, 
  bins = c(0, 5, 10, 20, 30, Inf)
)

# Create the choropleth map
(
choropleth <- basemap %>%
  addPolygons(
    data = fatal_crashes_2019_by_county,
    color = "white",
    weight = 1.5,
    opacity = 0.75,
    fillColor = ~color_pal(n_crashes), 
    fillOpacity = 0.75,
    dashArray = "2"
  ) %>%
    addLegend(
      data = fatal_crashes_2019_by_county, 
      pal = color_pal,
      values = ~n_crashes
    )
)
```

---
# Synced heatmaps of summer (L) vs. winter (R) fatal crashes

```{r synced_heatmaps, out.width = "100%"}
heatmap_summer <- basemap %>%
  addHeatmap(data = filter(fatal_crashes_2019, season == "summer"), radius = 10)
heatmap_winter <- basemap %>%
  addHeatmap(data = filter(fatal_crashes_2019, season == "winter"), radius = 10)
  
(
synced_heatmaps <- sync(heatmap_summer, heatmap_winter)
)
```


